name: looper

foundry:
  host: auto
  fork:
    base:
      mainnet:
        block_number: 43749913

node:
  base:
    mainnet:
      uri: https://mainnet.base.org

default_ecosystem: base
base:
  default_network: mainnet-fork
